services:
  department-demo-react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: 8001
    ports:
      - "8001:8001"
    command: ["serve", "-s", "dist", "-l", "8001"]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8001 || exit 1"]
      interval: 30s       
      timeout: 5s          
      retries: 3           
      start_period: 10s   
    restart: unless-stopped 